# Generated by Django 4.2.2 on 2023-06-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_model2_alter_model1_options_model1_pole3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model2',
            name='pole3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='site1.model1'),
            preserve_default=False,
        ),
    ]
