# Generated by Django 4.2.2 on 2023-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0003_model2_pole3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model2',
            name='pole3',
        ),
        migrations.AddField(
            model_name='model2',
            name='pole4',
            field=models.ManyToManyField(to='site1.model1'),
        ),
    ]
